### ISSUE TITLE
컨트롤러는 무조건 유즈케이스 호출해야하는가? 서비스 바로 호출해도 되는가?

### ISSUE THREAD

**Issue by yaeoni** [mash-up-kr/Dojo-Spring#50]
https://github.com/mash-up-kr/Dojo-Spring/pull/44#discussion_r1679563108

^ 위 코멘트 관련 논의

**Comment by yaeoni** [comment]
코드 예시
```kotlin
   @Transactional
    override fun update(command: MemberUseCase.UpdateCommand): MemberId {
        return memberService.update(
            MemberService.UpdateMember(
                memberId = command.memberId,
                profileImageId = command.profileImageId
            )
        )
    }
```

^ 요렇게 작성되어있는데, 사실 유즈케이스는 멤버 서비스"만" 호출할 뿐 별다른 어그리게이션 로직이라던가 작업을 해주지 않고 있음.
그러면, 유즈케이스 생략해도 되는거 아닐까?(==컨트롤러는 필요에 따라 서비스 레이어 직접 호출 가능하지않나) 란 생각을 했는데.. 여러분 생각도 궁금해요

일단 저는 불필요한 유즈케이스는 ㄴ생략해도 된다 파~

**Comment by wonlog-g** [comment]
오옹 그러면 후에 다른 서비스 클래스 호출이 필요한 경우가 생겼을 때 유즈케이스를 추가하게 되는 것일까요??

**Comment by xonmin** [comment]
> 코드 예시
> 
> ```kotlin
>    @Transactional
>     override fun update(command: MemberUseCase.UpdateCommand): MemberId {
>         return memberService.update(
>             MemberService.UpdateMember(
>                 memberId = command.memberId,
>                 profileImageId = command.profileImageId
>             )
>         )
>     }
> ```
> 
> ^ 요렇게 작성되어있는데, 사실 유즈케이스는 멤버 서비스"만" 호출할 뿐 별다른 어그리게이션 로직이라던가 작업을 해주지 않고 있음. 그러면, 유즈케이스 생략해도 되는거 아닐까?(==컨트롤러는 필요에 따라 서비스 레이어 직접 호출 가능하지않나) 란 생각을 했는데.. 여러분 생각도 궁금해요

요 케이스에 대해선 사실 단순히 서비스 하나만 의존하고 있어서 사실 말씀하신대로 유스케이스가 "굳이" 필요하진 않는 상황이라고 저도 동의합니당 

근데 추가적으로 봐야하는 건, Controller 에 직접적으로 서비스의 return 값이 그대로 전달된다는 것도 살펴보면 좋을 것 같아요 
물론, 요 케이스는 어차피 `MemberId` 만 그대로 전달되고 현재 저희는 DTO 에 domain ID 는 그대로 하고 있긴 한데,

만약 service fun 반환이 `Member` 라면 Controller 에서 Member 를 직접 import 하고 있게 되는데 요 부분에 대해선 다들 괜찮다고 생각하시는 지 궁금합니다 

<img width="857" alt="image" src="https://github.com/user-attachments/assets/dbe71049-6914-4267-9595-89fe4fbd43a4">

> 사실 저도 크게 상관없고, 쳐낼 것들이 많다보니 후딱후딱 처리하면 오케이라서 ㅎㅎ 의견들이 궁금하네요
> 저는 컨벤션 혹은 방향만 정해지면 따라갈 생각입니다

**Comment by toychip** [comment]
저도 크게 상관 없습니다!
정민님이 말씀하신 것처럼 Controller가 Member를 import하는 게 조금 신경쓰이긴 한데 다들 괜찮으신다면 저도 상관 없습니다~

**Comment by xonmin** [comment]
응답 모델에는 Domain 모델만 안들어가게만 하고, 이외 서비스 호출은 approve

**Comment by yaeoni** [comment]
하나의 도메인에만 의존하는 케이스는 service 바로 호출해도 가능

**Comment by yaeoni** [comment]
굿~
