### ISSUE TITLE
7월 4주차 스프린트 

### ISSUE THREAD

**Issue by xonmin** [mash-up-kr/Dojo-Spring#51]
24일, 25일 두 번에 나누어 회의 진행 

## 27일까지 ERD 개별적으로 다시 고안 및 설계 해오기 
-  내가 받은 알림 리스트 조회 API (레디스로 할래 DB로 할래) 요거 논의 27일에 
- [ ] 앉자마자 DB 연결 실시 
- [ ] 도메인 담당 (Web 이랑 1:1 매칭 or 1:2) 
- [ ] 개별 작업 실시 

## 8월 1일까지 스프린트 계획
- DB / Entity layer 붙이기 

## 안건

**Comment by xonmin** [comment]
- https://github.com/mash-up-kr/Dojo-Spring/pull/43
- https://github.com/mash-up-kr/Dojo-Spring/pull/48

**Comment by toychip** [comment]
#9 
#46

**Comment by wonlog-g** [comment]
- https://github.com/mash-up-kr/Dojo-Spring/pull/47
- 투표 남은 시간 조회 API (진행중)
